# Generated by Django 3.1.5 on 2021-01-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
