# Generated by Django 3.1.5 on 2021-01-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_auto_20210120_2128'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorModel',
            new_name='BookModel',
        ),
    ]
