# Generated by Django 3.1.5 on 2021-01-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20210120_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(default=0, upload_to='book/coversp'),
            preserve_default=False,
        ),
    ]
